---
title: "BST260FinalProject"
output: html_document
---


```{r}
library(tidyverse)
library(ggplot2)
library(rvest)
library(maps)
library(randomForest)
library(caret)
```

```{r}
# import datasets
library(gsheet)
#spreadsheet of data pulled from 2020 world happiness report (data for figure 2.1 in the report) 
url20 <- "https://docs.google.com/spreadsheets/d/1vkHkvnZFhtekjkYbF-y7uVo4oE36ROaqJx4lxVIkdq4/edit?usp=sharing"
dat20 <- gsheet2tbl(url20, sheetid = NULL)

#shiny
dat2_1 <- "https://docs.google.com/spreadsheets/d/1bAzkkXU3W7LALAzP2cnaahbf-s52kr8GvjJ3pIaK9Cs/edit?usp=sharing"
whr2_1 <- gsheet2tbl(dat2_1, sheetid = NULL)
```



```{r}
world_map = map_data("world")

#dat20[is.na(match(dat20$`Country name`, world_map$region)), ]

dat20 <- dat20 %>%
  mutate(new_names = recode(`Country name`,
    "United Kingdom" = "UK",
    "United States" = "USA",
    "Taiwan Province of China" = "Taiwan",
    "Trinidad and Tobago" = "Trinidad",
    "North Cyprus" = "Cyprus",
    "Hong Kong S.A.R. of China" = "Hong Kong",
    "Palestinian Territories" = "Palestine",
    "Congo (Brazzaville)" = "Democratic Republic of the Congo"
  )
  )

world_map <- within(world_map, region[region == "China" & subregion == "Hong Kong"] <- "Hong Kong")

world_map <- world_map %>%
  filter(region != "Antarctica") %>% 
  rename("Country" = region)


dat20 <- dat20 %>%
  rename("Country" = new_names)

combined_countries <- full_join(dat20, world_map)


combined_countries <- combined_countries %>% mutate(manual_fill = cut(`Ladder score`, 
                         breaks = c(2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, Inf),
                         labels = c("(2, 2.5]", "(2.5, 3]", "(3, 3.5]", "(3.5, 4]", "(4, 4.5]",
                                    "(4.5, 5]", "(5, 5.5]", "(5.5, 6]", "(6, 6.5]", 
                                    "(6.5, 7]", "(7, 7.5]", "(7.5, 8]", ">8"), 
                         right = TRUE))
```
```{r}
whr2_1 <- whr2_1 %>% rename(GDP = `Log GDP per capita`,
                            "LifeExpectancy" = `Healthy life expectancy at birth`,
                            "SocialSupport" = `Social support`,
                            "PerceptionsOfCorruption" = `Perceptions of corruption`)
```


```{r}
library(sf)
library(ggrepel)
library(ggspatial)

topcities <- data.frame(Country = c("Taiwan", "Australia", "Mauritius", "Chile", "Canada", "Finland"), 
    lat = c(23.6978, -43.23242, -20.48486, -33.447487, 56.1394, 60.04068), 
    lng = c(120.9605, 147.3488, 57.65127, -70.673676, -106.3468, 20.61133),
    level = c("happiest", "happiest", "happiest", "happiest", "happiest", "happiest"))

(topcities <- st_as_sf(topcities, coords = c("lng", "lat"), remove = FALSE, 
    crs = 4326, agr = "constant"))

lowcities <- data.frame(Country = c("Venezuela", "Haiti", "South Sudan", "Ukraine", "Afghanistan"), 
    lat = c(6.4238, 18.9715, 6.8770, 48.3794, 33.9391), 
    lng = c(-66.5897, -72.2852, 31.3070, 31.1656, 67.6100),
    level = c("saddest", "saddest", "saddest", "saddest", "saddest"))

(lowcities <- st_as_sf(lowcities, coords = c("lng", "lat"), remove = FALSE, 
    crs = 4326, agr = "constant"))

mostleast <- rbind(topcities, lowcities)

ggplot() +
  geom_polygon(combined_countries, mapping = aes(x = long, y = lat, group = group, fill = manual_fill)) +
  geom_text_repel(data = mostleast, aes(x = lng, y = lat, label = Country, color = level), 
                  size = 3,
                  fontface = "bold",
                  nudge_x = c(25, -1.5, 15, -13, -40, -16, 8, 3, 46, 3, 2),
                  nudge_y = c(-5, -15, 7, 3, -7, 13, 10, 7, -3, 26, 45),
                  min.segment.length = unit(0, "lines")) +
  geom_sf(data = topcities, alpha = 0.5, size = 0.5, color = "salmon3") +
  geom_sf(data = lowcities, alpha = 0.5, size = 0.5, color = "dodgerblue4") +
  ggtitle("Happiness Levels Across the World in 2019 (based on WHR 2020)") +
  scale_fill_manual(name = "Cantrill Ladder Score", 
                     values = c("dodgerblue4",
                                "dodgerblue3", 
                                "lightskyblue2",
                                "paleturquoise3",
                                "lightcyan3",
                                "honeydew2",
                                "khaki1",
                                "gold1",
                                "goldenrod1",
                                "darkgoldenrod2",
                                "salmon3"),
                    na.value = "gray") +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 7)) +
  guides(shape = guide_legend(override.aes = list(size = 5))) +
  theme(panel.grid.major = element_blank(), 
        panel.background = element_blank(),
        axis.title = element_blank(), 
        axis.text = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank())
  
```


```{r}
# whr2_1$year <- as.Date(whr2_1$year)
# whr2_1 %>% filter (`Country name` == "Afghanistan") %>% 
#   ggplot(aes(x = year, y = `Life Ladder`, color = `Country name`)) +
#     geom_line() +
#     scale_x_continuous(breaks = c(2007, 2020))
```

```{r}
#dataframe for machine learning
#predicting ladder score based on other variables

#do not need country and year
machine_whr <- whr2_1 %>%
  select(3:12)

#make empty rows 0 for countries with no reporting for specific countries
#reasoning is that those countries might not allow residents to answer those questions or residents are less inclined to answer them
machine_whr$`Confidence in national government`[is.na(machine_whr$`Confidence in national government`)] <- 0
machine_whr$PerceptionsOfCorruption[is.na(machine_whr$PerceptionsOfCorruption)] <- 0

#drop remaining rows with missing values and rename
full_machine_whr <- machine_whr %>%
  drop_na() %>%
  rename(FreedomLifeChoices = `Freedom to make life choices`,
         PositiveAffect = `Positive affect`,
         NegativeAffect = `Negative affect`,
         Confidence = `Confidence in national government`,
         LifeLadder = `Life Ladder`)

set.seed(1)

help(sample)

train_set <- sample(1:nrow(full_machine_whr), as.integer(nrow(full_machine_whr)*0.8))

fit_forest <- randomForest(formula = LifeLadder ~., data = full_machine_whr, subset = train_set)

predict_forest <- predict(fit_forest, newdata = full_machine_whr[-train_set, ])

test = full_machine_whr[-train_set, "LifeLadder"]

plot(predict_forest, pull(test, 1))

```
