---
title: "BST260WHR project"
author: "Sung-An Tai"
date: "2020/11/27"
output: html_document
---
```{r}
library(tidyverse)
library(readxl) 
library(gsheet)
library(MASS)
library(ggplot2)
library(grid)
library(gridExtra)

```


```{r}
# Read WHR20_DataForFigure2.1.xls (2017~2019 average) and WHR20_DataForTable2.1.xls (2008~2019 with additional variables)
# Main dependent variable: Ladder score, independent variable: `Logged GDP per capita`+`Social support`+`Healthy life expectancy`+`Freedom to make life choices`+`Generosity`+`Perceptions of corruption`
whr20 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1jVOpMfl94xDmip0NrJEXORoFK4RBfB7leDVzyJnk47w/edit#gid=28299357", sheetid = NULL)
whr_all <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1oMzplKOmjs0hKKmXKqOCM90CvPsS7aCIj1adox0nvNU/edit#gid=1261774380", sheetid = NULL)
names(whr20)

# Main model for fig 2.1 in the WHR 2020 report, but they used pooled OLS regression specific for panel analysis, rather than plain multiple regression
mod1 <- lm(`Ladder score` ~ `Logged GDP per capita`+
             `Social support`+`Healthy life expectancy`+
             `Freedom to make life choices`+
             `Generosity`+
             `Perceptions of corruption`,
           data = whr20)
summary(mod1)
##After we ran multiple regression  on the data (2017-2019), we found that five out of six variables were significant. The only exception was generosity. Therefore, we have ran some scatter plots to see the relationship between happiness score (ladder score) and each variable. From the scatter plots below, we found that it seems that there was not a linear relationship between  generosity and happiness score and between percpetions of corruption and happiness score.


p_1 <- whr20 %>% 
  ggplot(aes(x= `Logged GDP per capita`, y= `Ladder score`)) +
    geom_point() +
    ylab("Happiness score")  +
    xlab("Logged GDP per capita") +
  ggtitle("Ladder vs GDP per Capita")

p_1


p_2 <- whr20 %>% 
  ggplot(aes(x= `Social support`, y= `Ladder score`)) +
    geom_point() +
    ylab("Happiness score")  +
    xlab("Social support") +
  ggtitle("Ladder vs Social Support")

p_2

p_3 <- whr20 %>% 
  ggplot(aes(x= `Healthy life expectancy`, y= `Ladder score`)) +
    geom_point() +
    ylab("Happiness score")  +
    xlab("Healthy life expectancy") +
  ggtitle("Ladder vs Healthy Life Expectancy")

p_3

p_4 <- whr20 %>% 
  ggplot(aes(x= `Freedom to make life choices`, y= `Ladder score`)) +
    geom_point() +
    ylab("Happiness score")  +
    xlab("Freedom to make life choices") +
  ggtitle("Ladder vs Freedom to make life choices")

p_4

p_5 <- whr20 %>%
    ggplot(aes(x= `Generosity`, y= `Ladder score`)) +
    geom_point() +
    ylab("Happiness score")  +
    xlab("Generosity") +
  ggtitle("Ladder vs Generosity")

p_5


p_6 <- whr20 %>% 
  ggplot(aes(x= `Perceptions of corruption`, y= `Ladder score`)) +
    geom_point() +
    ylab("Happiness score")  +
    xlab("Perceptions of corruption") +
  ggtitle("Ladder vs Perceptions of Corruption")
  
p_6


grid.arrange(p_1, p_2, p_3, p_4, p_5, p_6, nrow = 3)


##We have ran some plots to check the residual for the regression model(2017-2019 data).

# Residuals versus fitted plot
fitted(mod1)
residuals(mod1)
plot(fitted(mod1), residuals(mod1)) 
abline(a=0,b=0,col="pink")

# QQ Norm plot
qqnorm(residuals(mod1))
qqline(residuals(mod1),col="pink")



# We ran regression analyses for each year. 
# Model for 2019 only
whr19 <- whr_all %>% filter(year == 2019)
mod_19 <- lm(`Life Ladder` ~ `Log GDP per capita`+
             `Social support`+`Healthy life expectancy at birth`+
             `Freedom to make life choices`+
             `Generosity`+
             `Perceptions of corruption`,
           data = whr19)

summary(mod_19)

# Model from 2015 to 2019
modeling <- function(y){
  whr_df <- whr_all %>% filter(year == y) %>% dplyr::select(`Life Ladder`, `Log GDP per capita`,
             `Social support`, `Healthy life expectancy at birth`,
             `Freedom to make life choices`,
             `Generosity`,
             `Perceptions of corruption`) %>% drop_na()
  
  mod <- lm(`Life Ladder` ~ `Log GDP per capita`+
             `Social support`+`Healthy life expectancy at birth`+
             `Freedom to make life choices`+
             `Generosity`+
             `Perceptions of corruption`,
           data = whr_df)
  mod
}
years <- 2015:2019
mods.15to19 <- lapply(years, modeling)
names(mods.15to19) <- paste0("mod.", 2015:2019)
lapply(mods.15to19, summary)
lapply(mods.15to19, confint)

```
Should add analysis for effect modification.

Model backward selection:
```{r}
# backward selection for 2017~2019 model and 2019 model
mod1_bkwd <- step(mod1, direction = "backward")
summary(mod1_bkwd)

no.na.whr19 <- whr19 %>% dplyr::select(`Life Ladder`, `Log GDP per capita`,
             `Social support`, `Healthy life expectancy at birth`,
             `Freedom to make life choices`,
             `Generosity`,
             `Perceptions of corruption`) %>% drop_na()
mod_19_noNA <- lm(`Life Ladder` ~ `Log GDP per capita`+
             `Social support`+`Healthy life expectancy at birth`+
             `Freedom to make life choices`+
             `Generosity`+
             `Perceptions of corruption`,
           data = no.na.whr19)
mod_19_bckwd <- step(mod_19_noNA, direction = "backward")
s_19 <- summary(mod_19_bckwd)

# backward selection from 2015 to 2019
backward.select <- function(y){
  whr_df <- whr_all %>% filter(year == y) %>% dplyr::select(`Life Ladder`, `Log GDP per capita`,
             `Social support`, `Healthy life expectancy at birth`,
             `Freedom to make life choices`,
             `Generosity`,
             `Perceptions of corruption`) %>% drop_na()
  
  mod <- lm(`Life Ladder` ~ `Log GDP per capita`+
             `Social support`+`Healthy life expectancy at birth`+
             `Freedom to make life choices`+
             `Generosity`+
             `Perceptions of corruption`,
           data = whr_df)
  mod.backward <- step(mod, direction = "backward")
  mod.backward
}

backward.select(2015)
backward.select(2016)
```
##visualize cantril ladder by year
```{r}
# Happiness by year of all countries
whr_all %>% ggplot(aes(x = year, y = `Life Ladder`, color = `Country name`)) +
                geom_line() +
                ylab("Cantril Ladder") +
                ggtitle("Happiness") +
                scale_color_discrete(name = "Country") +
                theme(axis.text.x = element_text(angle = 70, hjust =1), legend.position = "none") +
                scale_x_continuous(breaks = seq(2005, 2019, by = 1)) +
                xlab("Year")

# Categorize by GDP, divide into 4 parts
whr_gdp <- whr_all %>% filter(!is.na(`Log GDP per capita`))
q_gdp <- whr_gdp %>% summarise(q1 = quantile(`Log GDP per capita`)[2], q3 = quantile(`Log GDP per capita`)[4], mean = mean(`Log GDP per capita`))
quantile(whr_gdp$`Log GDP per capita`)
whr_gdp <- whr_gdp %>% mutate(gdp_cat = cut(`Log GDP per capita`, breaks = c(-Inf, q_gdp[1], q_gdp[3], q_gdp[2], Inf), labels=c(0,1,2,3)))

# We find that full regression model often have insignificant coefficient of Generosity. We tried to stratify according
whr_gdp %>% filter(gdp_cat == 0) %>% ggplot(aes(x = year, y = `Life Ladder`, color = `Country name`)) + geom_line() + theme(legend.position = "none")

whr_gdp %>% filter(gdp_cat==3, year == 2018) %>% ggplot(aes(x = `Generosity`, y = `Life Ladder`)) + geom_point(color = "blue")
mod_gdp3_2018<- lm(`Life Ladder` ~ `Log GDP per capita`+
             `Social support`+`Healthy life expectancy at birth`+
             `Freedom to make life choices`+
             `Generosity`+
             `Perceptions of corruption`, data = whr_gdp %>% filter(gdp_cat==3, year == 2018))
summary(mod_gdp3_2018)
```


